// Code generated by mockery v2.10.4. DO NOT EDIT.

package events

import (
	bot "github.com/cinehouse/bot/app/bot"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageLogger is an autogenerated mock type for the MessageLogger type
type MockMessageLogger struct {
	mock.Mock
}

// Save provides a mock function with given fields: msg
func (_m *MockMessageLogger) Save(msg *bot.Message) {
	_m.Called(msg)
}
